services:
  nginx:
    image: ${NGINX_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: always
    env_file:
      - .env
    links:
      - php-fpm:php
    depends_on:
      - php-fpm
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-ssl.rule=Host(`${PROJECT_HOST}`) || Host(`www.${PROJECT_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-ssl.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-ssl.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-ssl.tls.certresolver=${PROJECT_CERT_RESOLVER}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-ssl.middlewares=${PROJECT_SSL_MIDDLEWARES}"

      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${PROJECT_HOST}`) || Host(`www.${PROJECT_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=http"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${PROJECT_MIDDLEWARES}"

      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - &www-volume ../:/var/www:cached
    networks:
      - zerxus
  php-fpm:
    ports:
      - 5173:5173
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-hmr-tls.rule=Host(`hmr.${PROJECT_HOST}`) || Host(`www.hmr.${PROJECT_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-hmr-tls.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-hmr-tls.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-hmr-tls.tls.certresolver=${PROJECT_CERT_RESOLVER}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-hmr-tls.middlewares=${PROJECT_SSL_MIDDLEWARES},cors-allow@file"
    build:
      context: images/php
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
    restart: always
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal idekey=PHPSTORM start_with_request=yes
      PHP_IDE_CONFIG: serverName=${COMPOSE_PROJECT_NAME}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    working_dir: /var/www
    env_file:
      - ../.env
    volumes:
      - ../../../homeserver/config/php-fpm/:/usr/local/etc/php/conf.d/common/:ro
      - ./config/php-fpm/${PHP_ENV}/:/usr/local/etc/php/conf.d/site/:ro
      - *www-volume
      - &msmtp-volume ../../../homeserver/config/msmtp/msmtprc:/etc/msmtprc:ro
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:ro
    external_links:
      - ${COMPOSE_PROJECT_NAME}-nginx:${PROJECT_HOST}
    networks:
      - zerxus
    user: "${UID}:${GID}"

networks:
  zerxus:
    external: true
    name: ${COMPOSE_COMMON_PROJECT_NAME}_${COMPOSE_NETWORK_NAME}
